### ISSUE TITLE
CoWFC Installer Error

### ISSUE THREAD

**Issue by jmfindorff** [EnergyCube/dwc_network_server_emulator#1]
I tried using your version of the CoWFC Installer, but, the installer crashes with an unexpected end of file syntax error. It also says that the error is located at the line 505, even though when I looked at the installer file in GitHub, the file ends at line 504, I might be wrong though.
![Error CoWFC](https://user-images.githubusercontent.com/34373903/66724191-ff241700-edf0-11e9-8347-0756c2c5c859.png)

**Comment by jmfindorff** [comment]
I figured out what the problem was. There is a syntax error when you tried to do an else if statement, you're supposed to use elif, not else and then a nested if.

**Comment by EnergyCube** [comment]
I just  [update](https://github.com/EnergyCube/cowfc_installer/commit/cc673b707c2fea1ce30a7b2af4ad011f252ffcdf) the CoWFC install script (not tested yet)
